### ISSUE TITLE
NameError: uninitialized constant ActsAsTree::TreeView

### ISSUE THREAD

**Issue by ltfschoen** [amerine/acts_as_tree#71]
I'm using Rails 5.1.3. When I test in Rails Console as follows I get error `NameError: uninitialized constant ActsAsTree::TreeView`.
```
$ bundle exec rails c
Running via Spring preloader in process 49432
Loading development environment (Rails 5.1.4)
irb(main):001:0> user1 = User.create(email: 'a@a.com', password: '12345678', encrypted_password: '12345678')
   (0.2ms)  BEGIN
  User Exists (1.3ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "a@a.com"], ["LIMIT", 1]]
  SQL (1.2ms)  INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["email", "a@a.com"], ["encrypted_password", "12345678"], ["created_at", "2017-11-05 14:18:21.095366"], ["updated_at", "2017-11-05 14:18:21.095366"]]
   (0.4ms)  COMMIT
=> #<User id: 1, email: "a@a.com", created_at: "2017-11-05 14:18:21", updated_at: "2017-11-05 14:18:21">
irb(main):002:0>   user1.profile = UserProfile.create(user_id: user1.id)
   (0.1ms)  BEGIN
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  SQL (1.1ms)  INSERT INTO "user_profiles" ("user_id", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["user_id", 1], ["created_at", "2017-11-05 14:18:27.586413"], ["updated_at", "2017-11-05 14:18:27.586413"]]
   (0.3ms)  COMMIT
  UserProfile Load (0.3ms)  SELECT  "user_profiles".* FROM "user_profiles" WHERE "user_profiles"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
=> #<UserProfile id: 1, user_id: 1, created_at: "2017-11-05 14:18:27", updated_at: "2017-11-05 14:18:27">
irb(main):003:0> token1 = SkillToken.create(name: "eat", weight: 1, user_profile_id: u.profile.id)
NameError: uninitialized constant ActsAsTree::TreeView
	from app/models/skill_token.rb:6:in `<class:SkillToken>'
	from app/models/skill_token.rb:1:in `<top (required)>'
	from (irb):3
irb(main):004:0> require 'acts_as_tree'
=> true
irb(main):005:0> token1 = SkillToken.create(name: "eat", weight: 1, user_profile_id: u.profile.id)
NameError: uninitialized constant ActsAsTree::TreeView
```

I created the following models:
```
class SkillToken < ActiveRecord::Base
  belongs_to :profile, class_name: 'UserProfile'
  belongs_to :parent
  validates_presence_of :name

  extend ActsAsTree::TreeView
  acts_as_tree order: 'name'
end
```
```
class Parent < ApplicationRecord
  has_many :skill_tokens
end
```
```
class UserProfile < ApplicationRecord
  belongs_to :user
  has_many :skill_tokens
end
```
```
class ActsAsTree < ApplicationRecord
  belongs_to :parent_id
end
```
```
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, class_name: 'UserProfile'
  # has_many :skill_tokens, :through => :profile
  delegate :skill_tokens, :to => :profile
end
```

I created the following relevant migrations and migrated them into PSQL with `rails db:drop db:create db:migrate`:
```
class CreateSkillTokens < ActiveRecord::Migration[5.1]
  def change
    create_table :skill_tokens do |t|
      t.string :name
      t.decimal :amount
      t.decimal :weight
      t.references :parent, foreign_key: true
      t.references :user_profile, foreign_key: true

      t.timestamps
    end
  end
end
```
```
class CreateParents < ActiveRecord::Migration[5.1]
  def change
    create_table :parents do |t|

      t.timestamps
    end
  end
end
```

**Comment by felixbuenemann** [comment]
What version of the gem are you using? (check your Gemfile.lock)

**Comment by ltfschoen** [comment]
acts_as_tree (2.7.0)
   activerecord (>= 3.0.0)

[This branch of my Git repo is where the error occurs](https://github.com/peerism/peerai-backend/compare/feature/7-associations-for-skill-and-sub-skill-tokens?expand=1)

**Comment by felixbuenemann** [comment]
The output posted above says rails 5.1.4. Maybe you forgot to run `spring stop` after updating gems?

Another idea is that you have a conflicting file "acts_as_tree.rb" in you load path, eg. from another gem that is loaded instead of "lib/acts_as_tree.rb" from this gem because it comes first in the load path.

**Comment by felixbuenemann** [comment]
The conflicting file is `app/models/acts_as_tree.rb` rename the file and constant to something else.

**Comment by felixbuenemann** [comment]
Btw. the `belongs_to :parent` association is automatically created if you call the `acts_as_tree` class method, so there's no need to use a common superclass for that.

**Comment by ltfschoen** [comment]
Thanks @felixbuenemann. I made the changes that you suggested. 
The solution was to remove Spring from the Gemfile as follows, then run `bundle install`. My Gemfile was changed as follows:
```
group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring

  # Remove since causes error: `NameError: uninitialized constant SkillToken::ActsAsTree`
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
end
```
I was then able to go into Rails Console and got the following response:
```
$ bundle exec rails c
Loading development environment (Rails 5.1.4)
irb(main):001:0> SkillToken
=> SkillToken (call 'SkillToken.connection' to establish a connection)
```
